name: First name

on: workflow_dispatch

jobs:
  First-job:
    runs-on: ubuntu-latest
    steps:
      - name: OS-Name
        run: sudo cat /etc/os-release

      - name: HostName
        run: sudo hostname
      - name: pathdetails
        run: |  
            sudo echo "$PATH"
            sudo echo "env"
